### ISSUE TITLE
Edit talents error

### ISSUE THREAD

**Issue by class2u** [Lethay/TalentedClassic#22]
Got this error when clicking talent icons with "Edit talents" checked.
I am using Talented Classic v191004 and zhTW Client.

5x Talented\learn-學習.lua:46: attempt to index global 'template' (a nil value)
Talented\learn-學習.lua:46: in function `LearnTalent'
Talented\view-檢視.lua:350: in function `UpdateTalent'
Talented\view-檢視.lua:341: in function `OnTalentClick'
Talented\ui\buttons.lua:24: in function <Talented\ui\buttons.lua:22>

Locals:
self = <table> {
 CreateTemplateMenu = <function> defined @Talented\ui\menu.lua:104
 defaults = <table> {
 }
 LoadAddOn = <function> defined @Talented\core.lua:66
 OpenOptionsFrame = <function> defined @Talented\ui\menu.lua:26
 MakeArrow = <function> defined @Talented\ui\arrows.lua:17
 GetTalentPrereqs = <function> defined @Talented\spell.lua:234
 spelldata = <table> {
 }
 UnregisterComm = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 HideTooltipInfo = <function> defined @Talented\tips.lua:134
 DataAddonLoaded = <function> defined @Talented\talents.lua:151
 GetDefaultMode = <function> defined @Talented\core.lua:260
 SetDefaultModulePrototype = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateTemplateName = <function> defined @Talented\core.lua:115
 GetMode = <function> defined @Talented\core.lua:46
 SetTemplate = <function> defined @Talented\core.lua:239
 SetMode = <function> defined @Talented\core.lua:50
 RegisterMessage = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Talented\core.lua:330
 hooks = <table> {
 }
 SendCommMessage = <function> defined @BugSack\Libs\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 mode = "edit"
 UnregisterAllComm = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Talented\Libs\AceHook-3.0\AceHook-3.0.lua:274
 OpenTemplate = <function> defined @Talented\core.lua:221
 OnEnable = <function> defined @Talented\core.lua:264
 GetTemplateStringClass = <function> defined @Talented\encode.lua:15
 MakeButton = <function> defined @Talented\ui\buttons.lua:75
 ImportTemplate = <function> defined @Talented\core.lua:199
 Pool = <table> {
 }
 UnregisterAllEvents = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 optionsFrame = <unnamed> {
 }
 Deserialize = <function> defined @BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 MakeActionMenu = <function> defined @Talented\ui\menu.lua:363
 TalentView = <table> {
 }
 GetName = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 views = <table> {
 }
 name = "Talented"
 UpdateView = <function> defined @Talented\viewmode.lua:90
 GetTalentInfo = <function> defined @Talented\talents.lua:195
 Disable = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Talented\options.lua:62
 Unhook = <function> defined @Talented\Libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Talented\core.lua:6
 UncompressSpellData = <function> defined @Talented\spell.lua:96
 SetOption = <function> defined @Talented\options.lua:55
 UpdateCurrentTemplate = <function> defined @Talented\viewmode.lua:44
 Serialize = <function> defined @BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:122
 Debug = <function> defined @Talented\core.lua:14
 EnableUI = <function> defined @Talented\ui\base.lua:362
 MakeTalentFrame = <function> defined @Talented\ui\trees.lua:99
 R

**Comment by Lethay** [comment]
Huh. I had disabled the "Confirm Learn" option on my client and so never noticed this problem. I've fixed it, I hope, but I haven't had a chance to test it, as I'm going to work and there's no way I'm playing the game to level up and test it. Please let me know if it works.

**Comment by class2u** [comment]
It is still not working in v191007. The error message is

4x Talented\learn-學習.lua:52: attempt to index global 'template' (a nil value)
Talented\learn-學習.lua:52: in function `LearnTalent'
Talented\view-檢視.lua:350: in function `UpdateTalent'
Talented\view-檢視.lua:341: in function `OnTalentClick'
Talented\ui\buttons.lua:24: in function <Talented\ui\buttons.lua:22>

Locals:
self = <table> {
 CreateTemplateMenu = <function> defined @Talented\ui\menu.lua:65
 defaults = <table> {
 }
 LoadAddOn = <function> defined @Talented\core.lua:66
 OpenOptionsFrame = <function> defined @Talented\ui\menu.lua:26
 MakeArrow = <function> defined @Talented\ui\arrows.lua:17
 GetTalentPrereqs = <function> defined @Talented\spell.lua:234
 UnregisterComm = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 HideTooltipInfo = <function> defined @Talented\tips.lua:134
 DataAddonLoaded = <function> defined @Talented\talents.lua:151
 GetDefaultMode = <function> defined @Talented\core.lua:260
 SetDefaultModulePrototype = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateTemplateName = <function> defined @Talented\core.lua:115
 GetMode = <function> defined @Talented\core.lua:46
 SetTemplate = <function> defined @Talented\core.lua:239
 SetMode = <function> defined @Talented\core.lua:50
 RegisterMessage = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Talented\core.lua:330
 hooks = <table> {
 }
 SendCommMessage = <function> defined @BugSack\Libs\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 mode = "edit"
 UnregisterAllComm = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Talented\Libs\AceHook-3.0\AceHook-3.0.lua:274
 OpenTemplate = <function> defined @Talented\core.lua:221
 OnEnable = <function> defined @Talented\core.lua:264
 GetTemplateStringClass = <function> defined @Talented\encode.lua:15
 MakeButton = <function> defined @Talented\ui\buttons.lua:75
 ImportTemplate = <function> defined @Talented\core.lua:199
 Pool = <table> {
 }
 UnregisterAllEvents = <function> defined @!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 optionsFrame = <unnamed> {
 }
 Deserialize = <function> defined @BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 MakeActionMenu = <function> defined @Talented\ui\menu.lua:363
 TalentView = <table> {
 }
 GetName = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 views = <table> {
 }
 name = "Talented"
 UpdateView = <function> defined @Talented\viewmode.lua:90
 GetTalentInfo = <function> defined @Talented\talents.lua:195
 Disable = <function> defined @!!!EaseAddonController\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Talented\options.lua:62
 Unhook = <function> defined @Talented\Libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Talented\core.lua:6
 UncompressSpellData = <function> defined @Talented\spell.lua:96
 SetOption = <function> defined @Talented\options.lua:55
 UpdateCurrentTemplate = <function> defined @Talented\viewmode.lua:44
 Serialize = <function> defined @BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:122
 Debug = <function> defined @Talented\core.lua:14
 EnableUI = <function> defined @Talented\ui\base.lua:362
 MakeTalentFrame = <function> defined @Talented\ui\trees.lua:99
 RegisterComm = <function> de

**Comment by Lethay** [comment]
Ha. It's like remote debugging. Try now.

**Comment by class2u** [comment]
It works fine now in v191007b. Thank you so much!

**Comment by Lethay** [comment]
And thank you for your help!
